In [1]:
#Source: https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/Part%201%20-%20Tensors%20in%20PyTorch%20(Exercises).ipynb
#import pytorch library
import torch

In [2]:
#Define the sigmoid activtion function
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))

##creates a tensor with shape (1, 5), one row and five columns, 
##that contains values randomly distributed according to the normal distribution 
##with a mean of zero and standard deviation of one.

# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [4]:
#investigate the shape of tensor
features.shape


torch.Size([1, 5])

In [5]:
# weights.view(a, b) will return a new tensor with the same data as weights with size (a, b).
weights.view(5,1)


#weights.reshape(a, b) will return a new tensor with the same data as weights with size (a, b) 
#sometimes, and sometimes a clone, as in it copies the data to another part of memory.

#weights.resize_(a, b) returns the same tensor with a different shape. 
#However, if the new shape results in fewer elements than the original tensor, 
#some elements will be removed from the tensor (but not from memory). 
#If the new shape results in more elements than the original tensor, new elements will be uninitialized in memory. 
#Here I should note that the underscore at the end of the method denotes that this method is performed in-place. 


tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [6]:
## Calculate the output of this network using the weights and bias tensors

#To calculate the output of the network:
#Take the inputs and multiply by the weights before adding the bias 
#and using the activation funciton to transform the latter

def output(features, weights, bias): 
    #use matrix multiplication to weight features
    result = torch.matmul(features, weights.view(5,1))
    #add the bias
    result1 = bias + result
    #transform the result using the sigmoid activation function
    trans = activation(result1)
    return(trans)

In [7]:
#result of output function
output(features, weights, bias)

tensor([[0.1595]])

In [8]:
#Sameple solution - logic and answer aligns 
y = activation((features * weights).sum() + bias)
print(y)

tensor([[0.1595]])


In [9]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [12]:
#Calculate the output of the above multi layer network

#The basic principle is to weigh the inputs and add the bias before transforming using the activation function

#Run from input layer to the hidden layer 
resulting1 = activation(torch.mm(features, W1) +B1)
##The weights matrix W1 already accoutns for the 2 hidden nodes                        
                        
#run the above node outout through the hidden to the output layer                         
resulting2 = activation(torch.mm(resulting1,W2)+B2)

#Print the transformed output
print(resulting2) #-> Correct! 

tensor([[0.3171]])


In [11]:
#Sample Solution
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])
